application: k8s-gubernator
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F2

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /static
  static_dir: static
  application_readable: true

- url: .*
  script: main.app
  secure: always
